<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MightyFights_Prototype</RootNamespace>
    <AssemblyName>MightyFights</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MightyFights.Core\MightyFights.Core.csproj" />
  </ItemGroup>

</Project>
